<?php require __DIR__.'/includes/bootstrap.php'; $title='Website Packages & Payments'; $page='packages'; require __DIR__.'/includes/header.php'; ?>
<main><section class="page-hero"><div class="wrap"><span class="kicker">CLEAR PRICING</span><h1>Start with a package. Pay in the way that suits you.</h1><p>Pay the full project fee, reserve your start date with a 30% deposit, or request a tailored quote.</p></div></section><section class="section"><div class="wrap pricing">
<?php $features=[['starter',['Up to 5 pages','Responsive design','Contact form','Basic SEO']],['business',['Up to 10 pages','PHP + MySQL','Admin-ready structure','Advanced SEO foundations']],['ecommerce',['Product catalogue','Razorpay payments','Orders database','Admin dashboard']]]; foreach($features as [$slug,$items]): $p=$packages[$slug]; ?>
<article class="price-card <?= $slug==='business'?'featured':'' ?>"><?php if($slug==='business'): ?><span class="popular">POPULAR</span><?php endif; ?><small><?= e($p['name']) ?></small><h2><?= e($p['label']) ?></h2><p>Starting price</p><ul><?php foreach($items as $item): ?><li>✓ <?= e($item) ?></li><?php endforeach; ?></ul><button class="btn primary pay-button" data-package="<?= e($slug) ?>" data-type="full">Pay full amount</button><button class="btn outline pay-button" data-package="<?= e($slug) ?>" data-type="deposit">Pay 30% deposit</button></article>
<?php endforeach; ?></div><div class="wrap custom-pay"><div><span class="kicker">CUSTOM QUOTE</span><h2>Already received a quote?</h2><p>Enter the quote reference and approved amount to pay securely.</p></div><form id="quote-payment"><label>Quote reference<input name="quote_ref" required placeholder="QUOTE-1001"></label><label>Amount (₹)<input name="quote_amount" type="number" min="1000" required placeholder="25000"></label><button class="btn primary" type="submit">Pay quoted amount ↗</button></form></div></section></main>
<div class="modal" id="pay-modal" hidden><div class="modal-card"><button class="close" type="button">×</button><h2>Complete your details</h2><p>We’ll create a secure Razorpay order for your selected option.</p><form id="payment-form"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="package"><input type="hidden" name="payment_type"><input type="hidden" name="quote_ref"><input type="hidden" name="quote_amount"><label>Full name<input name="name" required autocomplete="name"></label><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Phone<input name="phone" required autocomplete="tel"></label><button class="btn primary" type="submit">Continue to payment</button><p class="form-note" aria-live="polite"></p></form></div></div>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script><script defer src="/assets/js/payments.js"></script>
<?php require __DIR__.'/includes/footer.php'; ?>

