import Link from "next/link";
import { ContactBand, ServiceGrid, Shell } from "./components";

export default function Home() {
  return <Shell><main>
    <section className="hero"><div className="hero-grid"></div><div className="orb orb-one"></div><div className="orb orb-two"></div><div className="container hero-inner">
      <div className="hero-copy"><span className="eyebrow">DIGITAL PARTNERS FOR GROWING BRANDS</span><h1>Ideas that <em>rise.</em><br/>Digital that <strong>delivers.</strong></h1><p>We design and develop purposeful websites that move businesses forward—from the first sketch to long after launch.</p><div className="hero-actions"><Link className="btn primary" href="/contact">Start your project <span>↗</span></Link><Link className="text-link" href="/work">See our work <span>→</span></Link></div><div className="trusted"><div className="avatars"><i>A</i><i>S</i><i>+</i></div><span><b>Built for ambitious teams</b><small>Strategy, design & technology together</small></span></div></div>
      <div className="hero-art"><div className="art-card card-code"><div className="browser-dots"><i></i><i></i><i></i></div><code><b>&lt;build&gt;</b><br/>&nbsp;&nbsp;ideas: <em>true</em>;<br/>&nbsp;&nbsp;impact: <em>∞</em>;<br/><b>&lt;/build&gt;</b></code></div><div className="art-card card-stat"><span>Growth</span><strong>+184%</strong><div className="bars"><i></i><i></i><i></i><i></i><i></i></div></div><div className="art-ring"><span>AS</span></div><div className="float-label label-a">DESIGN</div><div className="float-label label-b">DEVELOP</div><div className="float-label label-c">DELIVER</div></div>
    </div><div className="hero-ticker"><div>WEB DEVELOPMENT <span>✦</span> RESPONSIVE DESIGN <span>✦</span> E-COMMERCE <span>✦</span> WORDPRESS <span>✦</span> SEO <span>✦</span> DIGITAL GROWTH</div></div></section>

    <section className="intro section"><div className="container intro-grid"><div><span className="eyebrow">WHO WE ARE</span><h2>Your business deserves more than just a website.</h2></div><div><p className="lead">Ascension Suppliers is a digital studio in Pune helping businesses build a stronger, smarter presence online.</p><p>We combine clear thinking, expressive design and dependable development to create websites that look distinct, work beautifully and support real growth.</p><Link className="arrow-link" href="/about">Discover our approach <span>↗</span></Link></div></div><div className="container stats"><div><strong>08</strong><span>Core digital<br/>services</span></div><div><strong>100%</strong><span>Responsive<br/>by design</span></div><div><strong>01</strong><span>Dedicated partner<br/>from start to finish</span></div></div></section>

    <section className="services section"><div className="container section-head"><div><span className="eyebrow">WHAT WE DO</span><h2>Everything your digital presence needs.</h2></div><p>Focused solutions that connect strategy, creative thinking and clean technology.</p></div><div className="container"><ServiceGrid limit={6}/><div className="center"><Link className="btn dark" href="/services">View all services <span>↗</span></Link></div></div></section>

    <section className="process section"><div className="container process-grid"><div className="process-sticky"><span className="eyebrow light">HOW WE WORK</span><h2>Clear steps.<br/>Better outcomes.</h2><p>No mystery, no unnecessary complexity—just a collaborative process built around momentum.</p><Link className="btn white" href="/contact">Plan your project <span>↗</span></Link></div><div className="steps"><article><span>01</span><div><h3>Discover</h3><p>We learn your business, customers, goals and opportunities.</p></div></article><article><span>02</span><div><h3>Define</h3><p>We shape the strategy, structure and visual direction.</p></div></article><article><span>03</span><div><h3>Design & Develop</h3><p>We turn the plan into a fast, intuitive digital experience.</p></div></article><article><span>04</span><div><h3>Deliver & Grow</h3><p>We launch carefully, support continuously and improve with insight.</p></div></article></div></div></section>

    <section className="work section"><div className="container section-head"><div><span className="eyebrow">SELECTED WORK</span><h2>Digital experiences with a reason to exist.</h2></div><Link className="arrow-link" href="/work">View all work <span>↗</span></Link></div><div className="container work-grid"><article className="work-card work-purple"><div className="mock-window"><span></span><div className="mock-body"><b>nourish.</b><h3>Better food.<br/>Brighter days.</h3><i></i></div></div><small>E-COMMERCE · BRAND EXPERIENCE</small><h3>Nourish Market</h3></article><article className="work-card work-orange"><div className="mock-phone"><div><small>HABIT</small><strong>Your day,<br/>in rhythm.</strong><i></i></div></div><small>MOBILE-FIRST · PRODUCT DESIGN</small><h3>Habit Health</h3></article></div></section>
    <ContactBand />
  </main></Shell>;
}
